---
platform: linux

image_resource:
  type: docker-image
  source: { repository: ubuntu }

inputs:
- name: source-code
- name: fly-release

params:
  concourse-url:
  concourse-team:
  concourse-username:
  concourse-password:

run:
  path: bash
  args: [./source-code/ci/tasks/seed-task.sh]