---
platform: linux

image_resource:
  type: docker-image
  source: { repository: ubuntu }

inputs:
- name: source-code
- name: fly-release

params:
  concourse_url:
  concourse_team:
  concourse_username:
  concourse_password:

run:
  path: ./source-code/ci/tasks/seed-task.sh