resources:
- name: source-code
  type: git
  source: 
    uri: https://github.com/li3/concourse-ci-sandbox.git
    branch: master
- name: fly-release
  type: github-release
  source:
    owner: concourse
    repository: concourse
jobs:
- name: seed
  plan:
  - get: source-code
    trigger: true
  - get: fly-release
    params:
      globs:
      - fly_linux_amd64
  - task: seed-task
    file: source-code/ci/tasks/seed-task.yml
    params:
      concourse-url: {{concourse-url}}
      concourse-team: {{concourse-team}}
      concourse-username: {{concourse-username}}
      concourse-password: {{concourse-password}}

- name: hello-world
  plan:
  - get: source-code
    trigger: true
    passed: [seed]
  - task: hello-task
    file: source-code/ci/tasks/say-hello-world.yml